![image.png](attachment:image.png)

![image-3.png](attachment:image-3.png)

In [ ]:
"""
입력 특징 : 공부시간, 출석일수, 과제제출횟수
출력 : 시험점수 선형모델
출력 : 시험점수
딥러닝 프레임워크 : 텐서플로(케라스), 파이토치, 카페
"""

'\n입력 특징 : 공부시간, 출석일수, 과제제출횟수\n출력 : 시험점수 선형모델\n출력 : 시험점수\n딥러닝 프레임워크 : 텐서플로(케라스), 파이토치, 카페\n'

![image.png](attachment:image.png)

In [ ]:
 import pandas as pd

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
# 뉴런을 만든상태
model=keras.Sequential([layers.Dense(units=1, input_shape=[3])])
model

![image-7.png](attachment:image-7.png)
![image-2.png](attachment:image-2.png)
![image-3.png](attachment:image-3.png)
![image-4.png](attachment:image-4.png)
![image-5.png](attachment:image-5.png)
![image-6.png](attachment:image-6.png)

In [ ]:
model=keras.Sequential([
layers.Dense(units=4,input_shape=[2], activation="relu"),
layers.Dense(units=3, activation="relu"),
layers.Dense(units=1, activation="sigmoid")
                  ])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 4)                 12

 dense_2 (Dense)             (None, 3)                 15

 dense_3 (Dense)             (None, 1)                 4

=================================================================
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
model.compile(optimizer="adam",loss="mae")

In [ ]:
import pandas as pd

In [ ]:
red_wine=pd.read_csv("red-wine.csv")
red_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
red_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [ ]:
df_train=red_wine.sample(frac=0.7, random_state=20231031)

In [ ]:
df_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1385,8.0,0.81,0.25,3.4,0.076,34.0,85.0,0.99668,3.19,0.42,9.2,5
1504,7.5,0.38,0.57,2.3,0.106,5.0,12.0,0.99605,3.36,0.55,11.4,6
1269,5.5,0.49,0.03,1.8,0.044,28.0,87.0,0.99080,3.50,0.82,14.0,8
1457,7.6,0.49,0.33,1.9,0.074,27.0,85.0,0.99706,3.41,0.58,9.0,5
671,8.2,0.73,0.21,1.7,0.074,5.0,13.0,0.99680,3.20,0.52,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1043,9.5,0.39,0.41,8.9,0.069,18.0,39.0,0.99859,3.29,0.81,10.9,7
1130,9.1,0.60,0.00,1.9,0.058,5.0,10.0,0.99770,3.18,0.63,10.4,6
363,12.5,0.46,0.63,2.0,0.071,6.0,15.0,0.99880,2.99,0.87,10.2,5
386,7.8,0.54,0.26,2.0,0.088,23.0,48.0,0.99810,3.41,0.74,9.2,6
1008,8.9,0.35,0.40,3.6,0.110,12.0,24.0,0.99549,3.23,0.70,12.0,7

In [ ]:
len(df_train)

1119

In [ ]:
df_train.index

Int64Index([1385, 1504, 1269, 1457,  671,  404, 1327, 1226,  803, 1563,
            ...
            1301,  120,  199,   40, 1052, 1043, 1130,  363,  386, 1008],
           dtype='int64', length=1119)

In [ ]:
df_test=red_wine.drop(df_train.index)

In [ ]:
len(df_test)

480

In [ ]:
df_train[:2]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1385,8.0,0.81,0.25,3.4,0.076,34.0,85.0,0.99668,3.19,0.42,9.2,5
1504,7.5,0.38,0.57,2.3,0.106,5.0,12.0,0.99605,3.36,0.55,11.4,6

![image-5.png](attachment:image-5.png)

# 정규화

In [ ]:
df_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1385,8.0,0.81,0.25,3.4,0.076,34.0,85.0,0.99668,3.19,0.42,9.2,5
1504,7.5,0.38,0.57,2.3,0.106,5.0,12.0,0.99605,3.36,0.55,11.4,6
1269,5.5,0.49,0.03,1.8,0.044,28.0,87.0,0.99080,3.50,0.82,14.0,8
1457,7.6,0.49,0.33,1.9,0.074,27.0,85.0,0.99706,3.41,0.58,9.0,5
671,8.2,0.73,0.21,1.7,0.074,5.0,13.0,0.99680,3.20,0.52,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1043,9.5,0.39,0.41,8.9,0.069,18.0,39.0,0.99859,3.29,0.81,10.9,7
1130,9.1,0.60,0.00,1.9,0.058,5.0,10.0,0.99770,3.18,0.63,10.4,6
363,12.5,0.46,0.63,2.0,0.071,6.0,15.0,0.99880,2.99,0.87,10.2,5
386,7.8,0.54,0.26,2.0,0.088,23.0,48.0,0.99810,3.41,0.74,9.2,6
1008,8.9,0.35,0.40,3.6,0.110,12.0,24.0,0.99549,3.23,0.70,12.0,7

In [ ]:
max_=df_train.max()
max_

fixed acidity            15.60000
volatile acidity          1.33000
citric acid               1.00000
residual sugar           15.50000
chlorides                 0.61100
free sulfur dioxide      72.00000
total sulfur dioxide    289.00000
density                   1.00369
pH                        4.01000
sulphates                 2.00000
alcohol                  14.00000
quality                   8.00000
dtype: float64

In [ ]:
min_=df_train.min()
min_

fixed acidity           4.60000
volatile acidity        0.12000
citric acid             0.00000
residual sugar          0.90000
chlorides               0.01200
free sulfur dioxide     1.00000
total sulfur dioxide    6.00000
density                 0.99007
pH                      2.74000
sulphates               0.33000
alcohol                 8.40000
quality                 3.00000
dtype: float64

In [ ]:
max_-min_

fixed acidity            11.00000
volatile acidity          1.21000
citric acid               1.00000
residual sugar           14.60000
chlorides                 0.59900
free sulfur dioxide      71.00000
total sulfur dioxide    283.00000
density                   0.01362
pH                        1.27000
sulphates                 1.67000
alcohol                   5.60000
quality                   5.00000
dtype: float64

In [ ]:
# 열단위로 각각의 데이터에서 최소값 뺀것
df_train-min_

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1385,3.4,0.69,0.25,2.5,0.064,33.0,79.0,0.00661,0.45,0.09,0.8,2.0
1504,2.9,0.26,0.57,1.4,0.094,4.0,6.0,0.00598,0.62,0.22,3.0,3.0
1269,0.9,0.37,0.03,0.9,0.032,27.0,81.0,0.00073,0.76,0.49,5.6,5.0
1457,3.0,0.37,0.33,1.0,0.062,26.0,79.0,0.00699,0.67,0.25,0.6,2.0
671,3.6,0.61,0.21,0.8,0.062,4.0,7.0,0.00673,0.46,0.19,1.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1043,4.9,0.27,0.41,8.0,0.057,17.0,33.0,0.00852,0.55,0.48,2.5,4.0
1130,4.5,0.48,0.00,1.0,0.046,4.0,4.0,0.00763,0.44,0.30,2.0,3.0
363,7.9,0.34,0.63,1.1,0.059,5.0,9.0,0.00873,0.25,0.54,1.8,2.0
386,3.2,0.42,0.26,1.1,0.076,22.0,42.0,0.00803,0.67,0.41,0.8,3.0
1008,4.3,0.23,0.40,2.7,0.098,11.0,18.0,0.00542,0.49,0.37,3.6,4.0

In [ ]:
#  테스트 데이터에 작업

In [ ]:
#0에서 1사이로 스케일링됨
df_train=(df_train-min_)/(max_-min_)
df_test=(df_test-min_)/(max_-min_)

In [ ]:
df_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1385,0.309091,0.570248,0.25,0.171233,0.106845,0.464789,0.279152,0.485316,0.354331,0.053892,0.142857,0.4
1504,0.263636,0.214876,0.57,0.095890,0.156928,0.056338,0.021201,0.439060,0.488189,0.131737,0.535714,0.6
1269,0.081818,0.305785,0.03,0.061644,0.053422,0.380282,0.286219,0.053598,0.598425,0.293413,1.000000,1.0
1457,0.272727,0.305785,0.33,0.068493,0.103506,0.366197,0.279152,0.513216,0.527559,0.149701,0.107143,0.4
671,0.327273,0.504132,0.21,0.054795,0.103506,0.056338,0.024735,0.494126,0.362205,0.113772,0.196429,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...
1043,0.445455,0.223140,0.41,0.547945,0.095159,0.239437,0.116608,0.625551,0.433071,0.287425,0.446429,0.8
1130,0.409091,0.396694,0.00,0.068493,0.076795,0.056338,0.014134,0.560206,0.346457,0.179641,0.357143,0.6
363,0.718182,0.280992,0.63,0.075342,0.098497,0.070423,0.031802,0.640969,0.196850,0.323353,0.321429,0.4
386,0.290909,0.347107,0.26,0.075342,0.126878,0.309859,0.148410,0.589574,0.527559,0.245509,0.142857,0.6
1008,0.390909,0.190083,0.40,0.184932,0.163606,0.154930,0.063604,0.397944,0.385827,0.221557,0.642857,0.8

In [ ]:
df_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,0.290909,0.628099,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.250000,0.4
9,0.263636,0.314050,0.36,0.356164,0.098497,0.225352,0.339223,0.567548,0.480315,0.281437,0.375000,0.4
10,0.190909,0.380165,0.08,0.061644,0.141903,0.197183,0.208481,0.428047,0.425197,0.125749,0.142857,0.4
16,0.354545,0.132231,0.56,0.061644,0.133556,0.478873,0.342756,0.501468,0.440945,0.251497,0.375000,0.8
17,0.318182,0.363636,0.28,0.054795,0.594324,0.211268,0.176678,0.494126,0.291339,0.568862,0.160714,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...
1581,0.145455,0.363636,0.09,0.054795,0.068447,0.323944,0.091873,0.290015,0.629921,0.161677,0.517857,0.4
1582,0.136364,0.491736,0.10,0.116438,0.068447,0.169014,0.074205,0.260646,0.653543,0.101796,0.625000,0.4
1587,0.109091,0.404959,0.11,0.061644,0.090150,0.239437,0.077739,0.349486,0.637795,0.197605,0.446429,0.6
1588,0.236364,0.446281,0.33,0.109589,0.093489,0.464789,0.339223,0.298825,0.417323,0.269461,0.785714,0.6
1591,0.072727,0.512397,0.09,0.054795,0.128548,0.211268,0.070671,0.290015,0.732283,0.137725,0.571429,0.6

In [ ]:
df_train=df_train.drop('quality', axis=1)
df_test=df_test.drop('quality', axis=1)

In [ ]:
y_train=red_wine["quality"]
y_test=red_wine["quality"]

In [ ]:
y_train = red_wine['quality'][df_train.index]
y_test = red_wine['quality'].drop(df_train.index)

In [ ]:
"""
y_train = red_wine['quality'][df_train.index]
y_test = red_wine['quality'].drop(df_train.index)

y_train =  red_wine['quality'][df_train.index]
y_test = red_wine['quality'][df_test.index]

y_train = red_wind.quality.drop(df_test.index)
y_test = red_wine.quality.drop(df_train.index)
"""

"\ny_train = red_wine['quality'][df_train.index]\ny_test = red_wine['quality'].drop(df_train.index)\n\ny_train =  red_wine['quality'][df_train.index]\ny_test = red_wine['quality'][df_test.index]\n\ny_train = red_wind.quality.drop(df_test.index)\ny_test = red_wine.quality.drop(df_train.index)\n"

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder()

In [ ]:
# get_dummies : 원핫인코딩

![image.png](attachment:image.png)

In [ ]:
pd.get_dummies(red_wine["quality"]) #6개 분류기, 소프트맥스, 확률로 나옴

      3  4  5  6  7  8
0     0  0  1  0  0  0
1     0  0  1  0  0  0
2     0  0  1  0  0  0
3     0  0  0  1  0  0
4     0  0  1  0  0  0
...  .. .. .. .. .. ..
1594  0  0  1  0  0  0
1595  0  0  0  1  0  0
1596  0  0  0  1  0  0
1597  0  0  1  0  0  0
1598  0  0  0  1  0  0

[1599 rows x 6 columns]

In [ ]:
y_test_ohe=ohe.fit_transform([y_test])

In [ ]:
y_test_ohe

<1x480 sparse matrix of type '<class 'numpy.float64'>'
	with 480 stored elements in Compressed Sparse Row format>

In [ ]:
y_train

1385    5
1504    6
1269    8
1457    5
671     5
       ..
1043    7
1130    6
363     5
386     6
1008    7
Name: quality, Length: 1119, dtype: int64

In [ ]:
y_test

1       5
9       5
10      5
16      7
17      5
       ..
1581    5
1582    5
1587    6
1588    6
1591    6
Name: quality, Length: 480, dtype: int64

In [ ]:
"""
품질 : 0 - 10까지 부여
범주형 : 원핫인코딩
"""

'\n품질 : 0 - 10까지 부여\n범주형 : 원핫인코딩\n'

In [ ]:
model=keras.Sequential([
    layers.Dense(512, activation='relu', input_shape=[11]),
    layers.Dense(512, activation='relu'),
    layers.Dense(512, activation='relu'),
    #layers.Dense(1)
    layers.Dense(11, activation="softmax")
])

In [ ]:
model.compile(
    optimizer='adam',
    loss='mae',
)

In [ ]:
1119/32

34.96875

In [ ]:
#35/35는 배치
model.fit(#batch_size=32
    df_train,y_train, epochs=10)

Epoch 1/10
35/35 [==============================] - 1s 5ms/step - loss: 5.5257
Epoch 2/10
35/35 [==============================] - 0s 5ms/step - loss: 5.5257
Epoch 3/10
35/35 [==============================] - 0s 4ms/step - loss: 5.5257
Epoch 4/10
35/35 [==============================] - 0s 4ms/step - loss: 5.5257
Epoch 5/10
35/35 [==============================] - 0s 4ms/step - loss: 5.5257
Epoch 6/10
35/35 [==============================] - 0s 4ms/step - loss: 5.5257
Epoch 7/10
35/35 [==============================] - 0s 4ms/step - loss: 5.5257
Epoch 8/10
35/35 [==============================] - 0s 4ms/step - loss: 5.5257
Epoch 9/10
35/35 [==============================] - 0s 5ms/step - loss: 5.5257
Epoch 10/10
35/35 [==============================] - 0s 5ms/step - loss: 5.5257

In [ ]:
y_test

1       5
9       5
10      5
16      7
17      5
       ..
1581    5
1582    5
1587    6
1588    6
1591    6
Name: quality, Length: 480, dtype: int64

In [ ]:
model.predict(df_test)

15/15 [==============================] - 0s 2ms/step

array([[0.09312673, 0.09243777, 0.09094376, ..., 0.08499349, 0.08907875,
        0.08863583],
       [0.09535468, 0.0920502 , 0.09155895, ..., 0.08437797, 0.09007517,
        0.08836523],
       [0.09436241, 0.09192275, 0.09039844, ..., 0.08611311, 0.08952471,
        0.08862388],
       ...,
       [0.09603667, 0.09161817, 0.09135486, ..., 0.08622523, 0.08709475,
        0.08893759],
       [0.09417793, 0.09201912, 0.09225778, ..., 0.08598236, 0.08811546,
        0.08842769],
       [0.09664507, 0.09194859, 0.09175387, ..., 0.08604676, 0.08663533,
        0.08862384]], dtype=float32)

# 당뇨병 데이터

In [ ]:
df=pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
x=df.iloc[:,0:8]
y=df.iloc[:,8]

In [ ]:
model=Sequential()

In [ ]:
#model.add(Dense(12,input_shape=[8])) or model.add(Dense(12,input_dim=8))

In [ ]:
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 12)                108

 dense_9 (Dense)             (None, 8)                 104

 dense_10 (Dense)            (None, 1)                 9

=================================================================
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x, y, epochs=10, batch_size=5)

Epoch 1/10
154/154 [==============================] - 1s 1ms/step - loss: 2.4294 - accuracy: 0.5599
Epoch 2/10
154/154 [==============================] - 0s 1ms/step - loss: 0.9962 - accuracy: 0.6250
Epoch 3/10
154/154 [==============================] - 0s 1ms/step - loss: 0.7725 - accuracy: 0.6289
Epoch 4/10
154/154 [==============================] - 0s 1ms/step - loss: 0.6828 - accuracy: 0.6589
Epoch 5/10
154/154 [==============================] - 0s 1ms/step - loss: 0.6389 - accuracy: 0.6745
Epoch 6/10
154/154 [==============================] - 0s 2ms/step - loss: 0.6208 - accuracy: 0.6758
Epoch 7/10
154/154 [==============================] - 0s 1ms/step - loss: 0.6081 - accuracy: 0.6797
Epoch 8/10
154/154 [==============================] - 0s 1ms/step - loss: 0.6011 - accuracy: 0.6836
Epoch 9/10
154/154 [==============================] - 0s 1ms/step - loss: 0.5920 - accuracy: 0.6875
Epoch 10/10
154/154 [==============================] - 0s 1ms/step - loss: 0.5863 - accuracy: 0.6927

# 아이리스

In [ ]:
df = pd.read_csv('iris3.csv')

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
X = df.iloc[:,0:4]
y = df.iloc[:,4]

In [ ]:
y = pd.get_dummies(y)

In [ ]:
y

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(16,  input_dim=4, activation="relu")),
model.add(Dense(8,activation="relu")),
model.add(Dense(3,activation="softmax"))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=40,batch_size=5)

Epoch 1/40
30/30 [==============================] - 0s 1ms/step - loss: 3.4476 - accuracy: 0.3333
Epoch 2/40
30/30 [==============================] - 0s 1ms/step - loss: 1.5595 - accuracy: 0.5333
Epoch 3/40
30/30 [==============================] - 0s 1ms/step - loss: 1.1483 - accuracy: 0.6667
Epoch 4/40
30/30 [==============================] - 0s 1ms/step - loss: 0.8875 - accuracy: 0.6667
Epoch 5/40
30/30 [==============================] - 0s 1ms/step - loss: 0.6958 - accuracy: 0.7667
Epoch 6/40
30/30 [==============================] - 0s 991us/step - loss: 0.6096 - accuracy: 0.8933
Epoch 7/40
30/30 [==============================] - 0s 1ms/step - loss: 0.5608 - accuracy: 0.8600
Epoch 8/40
30/30 [==============================] - 0s 1ms/step - loss: 0.5253 - accuracy: 0.9400
Epoch 9/40
30/30 [==============================] - 0s 1ms/step - loss: 0.5032 - accuracy: 0.8067
Epoch 10/40
30/30 [==============================] - 0s 1ms/step - loss: 0.4696 - accuracy: 0.9067
Epoch 11/40
30/30 [==============================] - 0s 998us/step - loss: 0.4536 - accuracy: 0.9133
Epoch 12/40
30/30 [==============================] - 0s 1ms/step - loss: 0.4313 - accuracy: 0.8933
Epoch 13/40
30/30 [==============================] - 0s 1ms/step - loss: 0.4214 - accuracy: 0.9133
Epoch 14/40
30/30 [==============================] - 0s 1ms/step - loss: 0.4081 - accuracy: 0.9067
Epoch 15/40
30/30 [==============================] - 0s 964us/step - loss: 0.3896 - accuracy: 0.9467
Epoch 16/40
30/30 [==============================] - 0s 997us/step - loss: 0.3743 - accuracy: 0.9333
Epoch 17/40
30/30 [==============================] - 0s 1ms/step - loss: 0.3656 - accuracy: 0.9533
Epoch 18/40
30/30 [==============================] - 0s 1ms/step - loss: 0.3548 - accuracy: 0.9400
Epoch 19/40
30/30 [==============================] - 0s 997us/step - loss: 0.3447 - accuracy: 0.9667
Epoch 20/40
30/30 [==============================] - 0s 1ms/step - loss: 0.3403 - accuracy: 0.9533
Epoch 21/40
30/30 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.9467
Epoch 22/40
30/30 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.9533
Epoch 23/40
30/30 [==============================] - 0s 1ms/step - loss: 0.3183 - accuracy: 0.9467
Epoch 24/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2976 - accuracy: 0.9667
Epoch 25/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2940 - accuracy: 0.9333
Epoch 26/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2846 - accuracy: 0.9533
Epoch 27/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2741 - accuracy: 0.9533
Epoch 28/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2661 - accuracy: 0.9533
Epoch 29/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2642 - accuracy: 0.9733
Epoch 30/40
30/30 [==============================] - 0s 753us/step - loss: 0.2568 - accuracy: 0.9533
Epoch 31/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2505 - accuracy: 0.9467
Epoch 32/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2351 - accuracy: 0.9533
Epoch 33/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2354 - accuracy: 0.9467
Epoch 34/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2292 - accuracy: 0.9667
Epoch 35/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2162 - accuracy: 0.9667
Epoch 36/40
30/30 [==============================] - 0s 1ms/step - loss: 0.2175 - accuracy: 0.9533
Epoch 37/40
30/30 [==============================] - 0s 803us/step - loss: 0.2064 - accuracy: 0.9533
Epoch 38/40
30/30 [==============================] - 0s 1ms/step - loss: 0.1977 - accuracy: 0.9733
Epoch 39/40
30/30 [==============================] - 0s 967us/step - loss: 0.1965 - accuracy: 0.9533
Epoch 40/40
30/30 [==============================] - 0s 1ms/step - loss: 0.1934 - accuracy: 0.9600

In [ ]:
import numpy as np

In [ ]:
model.predict(np.array([[5.9, 3.0, 5.1, 1.8]]))

1/1 [==============================] - 0s 41ms/step

array([[0.00092897, 0.21626927, 0.7828018 ]], dtype=float32)

In [ ]:
np.argmax([0.00092897, 0.21626927, 0.7828018 ])

2